name: Build and Push to ACR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ${{ vars.ACR_NAME }}.azurecr.io
  FRONTEND_IMAGE: frontend
  BACKEND_IMAGE: backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure Login using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Login to Azure Container Registry
      run: az acr login --name ${{ vars.ACR_NAME }}

    - name: Build and push frontend image
      working-directory: ./frontend
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:${{ github.sha }} .
        docker build -t ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:latest .
        docker push ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
        docker push ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:latest

    - name: Build and push backend image
      working-directory: ./backend
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:${{ github.sha }} .
        docker build -t ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:latest .
        docker push ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:${{ github.sha }}
        docker push ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:latest